// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken() {
  return window['go']['canvas']['APIClient']['GetAccessToken']();
}

export function GetAccountByID(arg1) {
  return window['go']['canvas']['APIClient']['GetAccountByID'](arg1);
}

export function GetAllEnrollmentsResultsByUserID(arg1) {
  return window['go']['canvas']['APIClient']['GetAllEnrollmentsResultsByUserID'](arg1);
}

export function GetAssignmentsByAccount(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetAssignmentsByAccount'](arg1, arg2);
}

export function GetAssignmentsByCourse(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetAssignmentsByCourse'](arg1, arg2);
}

export function GetAssignmentsResultsByUser(arg1) {
  return window['go']['canvas']['APIClient']['GetAssignmentsResultsByUser'](arg1);
}

export function GetCourseByID(arg1) {
  return window['go']['canvas']['APIClient']['GetCourseByID'](arg1);
}

export function GetCoursesByAccount(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetCoursesByAccount'](arg1, arg2);
}

export function GetCoursesByAccountID(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetCoursesByAccountID'](arg1, arg2);
}

export function GetEnrollmentsBySectionID(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetEnrollmentsBySectionID'](arg1, arg2);
}

export function GetEnrollmentsByUserID(arg1) {
  return window['go']['canvas']['APIClient']['GetEnrollmentsByUserID'](arg1);
}

export function GetSectionByID(arg1) {
  return window['go']['canvas']['APIClient']['GetSectionByID'](arg1);
}

export function GetSectionsByCourseID(arg1) {
  return window['go']['canvas']['APIClient']['GetSectionsByCourseID'](arg1);
}

export function GetSubmissions(arg1, arg2) {
  return window['go']['canvas']['APIClient']['GetSubmissions'](arg1, arg2);
}

export function GetUngradedSubmissionsByAccount(arg1) {
  return window['go']['canvas']['APIClient']['GetUngradedSubmissionsByAccount'](arg1);
}

export function GetUserBySisID(arg1) {
  return window['go']['canvas']['APIClient']['GetUserBySisID'](arg1);
}

export function LongRunningSleepFunc(arg1) {
  return window['go']['canvas']['APIClient']['LongRunningSleepFunc'](arg1);
}
