// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Do(arg1) {
  return window['go']['canvas']['APIClient']['Do'](arg1);
}
