// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {canvas} from '../models';

export function GetAccountByID(arg1:number):Promise<canvas.Account>;

export function GetAllEnrollmentsResultsByUserID(arg1:number):Promise<Array<canvas.EnrollmentResult>>;

export function GetAssignmentsByAccount(arg1:canvas.Account,arg2:string):Promise<Array<canvas.Assignment>>;

export function GetAssignmentsByCourseID(arg1:number,arg2:string):Promise<Array<canvas.Assignment>>;

export function GetAssignmentsResultsByUser(arg1:canvas.User):Promise<Array<canvas.AssignmentResult>>;

export function GetCourseByID(arg1:number):Promise<canvas.Course>;

export function GetCoursesByAccount(arg1:canvas.Account,arg2:string):Promise<Array<canvas.Course>>;

export function GetEnrollmentsBySectionID(arg1:number,arg2:Array<string>):Promise<Array<canvas.Enrollment>>;

export function GetEnrollmentsByUserID(arg1:number):Promise<Array<canvas.Enrollment>>;

export function GetQualifications():Promise<Array<canvas.Qualification>>;

export function GetSectionsByCourseID(arg1:number):Promise<Array<canvas.Section>>;

export function GetSectionsByID(arg1:number):Promise<canvas.Section>;

export function GetSubmissions(arg1:number,arg2:number):Promise<Array<canvas.Submission>>;

export function GetUngradedSubmissionsByAccount(arg1:canvas.Account):Promise<Array<canvas.Submission>>;

export function GetUserBySisID(arg1:string):Promise<canvas.User>;
