// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {canvas} from '../models';

export function GetQualifications():Promise<Array<canvas.Qualification>>;
