// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {canvas} from '../models';

export function ExportAssignmentsResults(arg1:Array<canvas.AssignmentResult>,arg2:string):Promise<void>;

export function ExportAssignmentsStatus(arg1:Array<canvas.Assignment>,arg2:canvas.Account):Promise<void>;
