// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAssignmentsResults(arg1, arg2) {
  return window['go']['main']['App']['ExportAssignmentsResults'](arg1, arg2);
}

export function ExportAssignmentsStatus(arg1, arg2) {
  return window['go']['main']['App']['ExportAssignmentsStatus'](arg1, arg2);
}

export function ExportEnrollmentsResults(arg1, arg2) {
  return window['go']['main']['App']['ExportEnrollmentsResults'](arg1, arg2);
}
